name: flame
channels:
  - default
  - rdkit
  - conda-forge 
  - chembl
dependencies:
  - pip
  - python=3.6
  - pandas
  - setuptools=>38.4.0
  - scikit-learn=>0.19.1
  - requests
  - rdkit
  - pyyaml
  - pytest
  - chembl_structure_pipeline
  - pip:
     - xgboost
     - django==2.2.8
     - djangorestframework
     - django-cors-headers
     - djangorestframework-yaml
     - "https://github.com/phi-grib/standardiser/archive/master.zip"
     - "https://github.com/josecarlosgomezt/nonconformist/archive/master.zip"