name: flame
channels:
  - default
  - rdkit
  - conda-forge
  - chembl
dependencies:
  - pip
  - python
  - setuptools
  - scikit-learn=1.5.2
  - imbalanced-learn
  - requests
  - rdkit
  - pyyaml
  - pytest
  - psycopg2
  - chembl_structure_pipeline
  - python-docx
  - openpyxl
  - appdirs
  - pip:
    - xgboost==1.4.2
    - django==2.2.8
    - djangorestframework
    - django-cors-headers
    - djangorestframework-yaml
    - python-keycloak
    - "https://github.com/phi-grib/standardiser/archive/master.zip"
    - "https://github.com/phi-grib/nonconformist/archive/master.zip"
