admin_email: admin@domain.org
admin_name: Admin Name
config_status: false
provider: My Organization
homepage: homepage@domain.org
model_repository_path: 
predictions_repository_path: 
space_repository_path: 
