admin_email: manuel.pastor@upf.edu
admin_name: Manuel Pastor
config_status: true
homepage: http://phi.upf.edu
model_repository_path: C:\Users\mpastor\Documents\soft\flame\flame\models
space_repository_path: C:\Users\mpastor\Documents\soft\flame\flame\spaces
#model_repository_path: /home/jcgomez/projects/internals/flame/flame/flame/models
model_repository_path: /home/jcgomez/projects/internals/flame/test
provider: UPF (Pompeu Fabra University)
