admin_email: admin@domain.org
admin_name: Admin Name
config_status: true
homepage: homepage@domain.org
models: X:\models\BSC\models
predictions: X:\models\BSC\predictions
profiles: X:\models\BSC\profiles
provider: My Organization
root_repository: X:\models\BSC
spaces: X:\models\BSC\spaces
