admin_email: admin@domain.org
admin_name: Admin Name
config_status: true
homepage: homepage@domain.org

model_repository_path: X:\soft\flame\flame\models
predictions_repository_path: X:\soft\flame\flame\predictions
provider: My Organization
space_repository_path: X:\soft\flame\flame\spaces

