admin_email: manuel.pastor@upf.edu
admin_name: Manuel Pastor
config_status: true
homepage: http://phi.upf.edu
model_repository_path: /mnt/e/synced/internals/flame/LQT_models/LQT_new/models
predictions_repository_path: /mnt/e/synced/internals/flame/LQT_models/LQT_new/predictions
provider: UPF (Pompeu Fabra University)
space_repository_path: /mnt/e/synced/internals/flame/LQT_models/LQT_new/spaces
