admin_email: manuel.pastor@upf.edu
admin_name: Manuel Pastor
config_status: true
homepage: http://phi.upf.edu
model_repository_path: D:\Usuarios\manuel\documentos\soft\flame\flame\models
provider: UPF
